import {
  CREATE_BUSSINESS_DETAILS,
  CREATE_PERSON_INFO_DETAILS,
  CREATE_BUSINESS_DOCUMENT,
  CREATE_EKYC,
  CREATE_CUSTOMER_WALLET,
} from "./post";

export default {
  CREATE_BUSSINESS_DETAILS,
  CREATE_PERSON_INFO_DETAILS,
  CREATE_BUSINESS_DOCUMENT,
  CREATE_EKYC,
  CREATE_CUSTOMER_WALLET,
};
