import {
  SIGN_IN,
  PRE_VALIDATE_SIGNIN,
  FORGET_PASSWORD,
  RESET_PASSWORD,
  SET_PASSWORD,
  RESET_PASSWORD_BY_USER,
  SEND_EMAIL_OTP,
  VERIFY_EMAIL_OTP,
  RESEND_EMAIL_OTP,
  SIGN_UP,
} from "./post";

import { VALIDATE_TOKEN, REFRESH_TOKEN } from "./get";

export default {
  SIGN_IN,
  SIGN_UP,
  PRE_VALIDATE_SIGNIN,
  FORGET_PASSWORD,
  VALIDATE_TOKEN,
  RESET_PASSWORD,
  SET_PASSWORD,
  REFRESH_TOKEN,
  RESET_PASSWORD_BY_USER,
  SEND_EMAIL_OTP,
  VERIFY_EMAIL_OTP,
  RESEND_EMAIL_OTP,
};
