import {
  GET_ALL_COUNTRIES,
  GET_ALL_COUNTRIES_GROUP_BY_REGIONS,
  GET_ALL_CURRENCIES,
} from "./get";

export default {
  GET_ALL_COUNTRIES,
  GET_ALL_COUNTRIES_GROUP_BY_REGIONS,
  GET_ALL_CURRENCIES,
};
