import {
  GET_ALL_SUBSCRIPTION_ORDER,
  GET_ALL_REDEMPTION_ORDER,
  EXPORT_SUBSCRIPTION_ORDER_AS_CSV,
  EXPORT_REDEMPTION_ORDER_AS_CSV,
  VIEW_ORDER_DETAILS,
} from "./get";
import { CANCEL_ORDER, CONFRIM_PAYMENT, SEND_PAYMENT } from "./put";

export default {
  GET_ALL_SUBSCRIPTION_ORDER,
  GET_ALL_REDEMPTION_ORDER,
  EXPORT_SUBSCRIPTION_ORDER_AS_CSV,
  EXPORT_REDEMPTION_ORDER_AS_CSV,
  VIEW_ORDER_DETAILS,
  CANCEL_ORDER,
  CONFRIM_PAYMENT,
  SEND_PAYMENT,
};
