import {
  GET_VALUATION_GRAPH,
  GET_ORDERS_GRAPH,
  GET_SUMMARY_RECENT_ACTIVITIES,
  GET_INVESTOR_DISTRIBUTION,
} from "./get";

export default {
  GET_VALUATION_GRAPH,
  GET_ORDERS_GRAPH,
  GET_SUMMARY_RECENT_ACTIVITIES,
  GET_INVESTOR_DISTRIBUTION,
};
