import { CREATE_TOKEN } from "./post";
import { UPDATE_TOKEN_STATUS, UPDATE_TOKEN_OFFERINGS,UPDATE_TOKEN_VALUATION } from "./put";
import { GET_TOKEN, GET_ISSUER_TOKENS } from "./get";

export default {
  CREATE_TOKEN,
  UPDATE_TOKEN_STATUS,
  UPDATE_TOKEN_OFFERINGS,
  GET_TOKEN,
  GET_ISSUER_TOKENS,
  UPDATE_TOKEN_VALUATION
};
