import {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
  GET_INVESTOR_LIST,
  GET_INVESTOR_LIST_AS_CSV,
  GET_TOKEN_DEPLOYMENT_COUNT,
  GET_ISSUER_APPROVAL_COUNT,
  GET_TOTAL_INVESTMENT_ISSUERS_INVESTORS_COUNT,
} from "./get";

export default {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
  GET_INVESTOR_LIST,
  GET_INVESTOR_LIST_AS_CSV,
  GET_TOKEN_DEPLOYMENT_COUNT,
  GET_ISSUER_APPROVAL_COUNT,
  GET_TOTAL_INVESTMENT_ISSUERS_INVESTORS_COUNT,
};
