import {
  GET_INVESTOR_COUNT_FOR_QUALIFY,
  GET_INVESTOR_DATA_FOR_QUALIFY,
} from "./get";
import { UPSERT_INVESTOR_STATUS } from "./put";

export default {
  GET_INVESTOR_COUNT_FOR_QUALIFY,
  GET_INVESTOR_DATA_FOR_QUALIFY,
  UPSERT_INVESTOR_STATUS,
};
