import {
  GET_INVESTOR_COUNT_FOR_QUALIFY,
  GET_INVESTOR_DATA_FOR_QUALIFY,
  EXPORT_INVESTOR_DATA_AS_CSV_FILE,
} from "./get";
import { UPSERT_INVESTOR_STATUS } from "./put";

export default {
  GET_INVESTOR_COUNT_FOR_QUALIFY,
  GET_INVESTOR_DATA_FOR_QUALIFY,
  UPSERT_INVESTOR_STATUS,
  EXPORT_INVESTOR_DATA_AS_CSV_FILE,
};
