import { CREATE_SUBSCRIPTION_ORDER, CREATE_REDEMPTION_ORDER } from "./post";
import { GET_SUBSCRIPTION_PAYMENT_DETAILS } from "./get";

export default {
  CREATE_SUBSCRIPTION_ORDER,
  GET_SUBSCRIPTION_PAYMENT_DETAILS,
  CREATE_REDEMPTION_ORDER,
};
