import {
  GET_TOKEN_HOLDINGS_GRAPH,
  GET_CURRENT_TOKEN_INVESTMENT,
  GET_DASHBOARD,
  GET_LAST_PERFORMANCE,
} from "./get";

export default {
  GET_TOKEN_HOLDINGS_GRAPH,
  GET_CURRENT_TOKEN_INVESTMENT,
  GET_DASHBOARD,
  GET_LAST_PERFORMANCE,
};
