import { CREATE_TOKEN_OFFERINGS } from "./post";
import { UPDATE_TOKEN_STATUS, UPDATE_TOKEN_OFFERINGS,UPDATE_TOKEN_VALUATION,UPDATE_TOKEN_OFFERING_STATUS } from "./put";
import { FIND_TOKEN, GET_ISSUER_TOKENS,GET_ALL_TOKENS } from "./get";

export default {
  CREATE_TOKEN_OFFERINGS,
  UPDATE_TOKEN_STATUS,
  FIND_TOKEN,
  UPDATE_TOKEN_OFFERINGS,
  GET_ISSUER_TOKENS,
  UPDATE_TOKEN_VALUATION,
  GET_ALL_TOKENS,
  UPDATE_TOKEN_OFFERING_STATUS
};
