import { CREATE_TOKEN_OFFERINGS } from "./post";
import { UPDATE_TOKEN_STATUS, UPDATE_TOKEN_OFFERINGS } from "./put";

export default {
  CREATE_TOKEN_OFFERINGS,
  UPDATE_TOKEN_STATUS,
  UPDATE_TOKEN_OFFERINGS,
};
