import { config } from "dotenv";
config({ path: ".env" });

const {
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  NODE_ENV,
  AUTH_API_LOCAL,
  INVESTOR_URL,
  ADMIN_URL,
  ISSUER_URL,
  ALERTSHUB_KEY,
  AWS_BUCKET_NAME,
  S3_END_PONIT,
  S3_ACCESS_KEY,
  S3_SECRET_KEY,
  ALERTHUB_ENDPOINT,
}: any = process.env;

export default {
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  NODE_ENV,
  AUTH_API_LOCAL,
  INVESTOR_URL,
  ADMIN_URL,
  ISSUER_URL,
  ALERTSHUB_KEY,
  AWS_BUCKET_NAME,
  S3_END_PONIT,
  S3_ACCESS_KEY,
  S3_SECRET_KEY,
  ALERTHUB_ENDPOINT,
};
