import { MINT_TOKEN,BURN_TOKEN } from "./post";
import { GET_ALL_TRANSACTION ,EXPORT_ALL_TRANSACTION_AS_CSV_FILE} from "./get";


export default {
  MINT_TOKEN,
  BURN_TOKEN,
  GET_ALL_TRANSACTION,
  EXPORT_ALL_TRANSACTION_AS_CSV_FILE
};
