import { master_countries } from "@prisma/client";

export const masterContries: { table: string; data: master_countries[] } = {
  table: "master_countries",
  data: [
    {
      id: 1,
      name: "Afghanistan",
      iso3: "AF",
      phone_code: "93",
      currency_code: "AFN",
      currency: "Afghan afghani",
      emoji: "🇦🇫",
      emoji_unicode: "U+1F1E6 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "؋",
    },
    {
      id: 2,
      name: "Aland Islands",
      iso3: "AX",
      phone_code: "+358-18",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇦🇽",
      emoji_unicode: "U+1F1E6 U+1F1FD",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 3,
      name: "Albania",
      iso3: "AL",
      phone_code: "355",
      currency_code: "ALL",
      currency: "Albanian lek",
      emoji: "🇦🇱",
      emoji_unicode: "U+1F1E6 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Lek",
    },
    {
      id: 4,
      name: "Algeria",
      iso3: "DZ",
      phone_code: "213",
      currency_code: "DZD",
      currency: "Algerian dinar",
      emoji: "🇩🇿",
      emoji_unicode: "U+1F1E9 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "دج",
    },
    {
      id: 5,
      name: "American Samoa",
      iso3: "AS",
      phone_code: "+1-684",
      currency_code: "USD",
      currency: "US Dollar",
      emoji: "🇦🇸",
      emoji_unicode: "U+1F1E6 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 6,
      name: "Andorra",
      iso3: "AD",
      phone_code: "376",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇦🇩",
      emoji_unicode: "U+1F1E6 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 7,
      name: "Angola",
      iso3: "AO",
      phone_code: "244",
      currency_code: "AOA",
      currency: "Angolan kwanza",
      emoji: "🇦🇴",
      emoji_unicode: "U+1F1E6 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Kz",
    },
    {
      id: 8,
      name: "Anguilla",
      iso3: "AI",
      phone_code: "+1-264",
      currency_code: "XCD",
      currency: "East Caribbean dollar",
      emoji: "🇦🇮",
      emoji_unicode: "U+1F1E6 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 9,
      name: "Antarctica",
      iso3: "AQ",
      phone_code: "672",
      currency_code: "AAD",
      currency: "Antarctican dollar",
      emoji: "🇦🇶",
      emoji_unicode: "U+1F1E6 U+1F1F6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 10,
      name: "Antigua and Barbuda",
      iso3: "AG",
      phone_code: "+1-268",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇦🇬",
      emoji_unicode: "U+1F1E6 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 11,
      name: "Argentina",
      iso3: "AR",
      phone_code: "54",
      currency_code: "ARS",
      currency: "Argentine peso",
      emoji: "🇦🇷",
      emoji_unicode: "U+1F1E6 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 12,
      name: "Armenia",
      iso3: "AM",
      phone_code: "374",
      currency_code: "AMD",
      currency: "Armenian dram",
      emoji: "🇦🇲",
      emoji_unicode: "U+1F1E6 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "֏",
    },
    {
      id: 13,
      name: "Aruba",
      iso3: "AW",
      phone_code: "297",
      currency_code: "AWG",
      currency: "Aruban florin",
      emoji: "🇦🇼",
      emoji_unicode: "U+1F1E6 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "ƒ",
    },
    {
      id: 14,
      name: "Australia",
      iso3: "AU",
      phone_code: "61",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇦🇺",
      emoji_unicode: "U+1F1E6 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 15,
      name: "Austria",
      iso3: "AT",
      phone_code: "43",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇦🇹",
      emoji_unicode: "U+1F1E6 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 16,
      name: "Azerbaijan",
      iso3: "AZ",
      phone_code: "994",
      currency_code: "AZN",
      currency: "Azerbaijani manat",
      emoji: "🇦🇿",
      emoji_unicode: "U+1F1E6 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "m",
    },
    {
      id: 18,
      name: "Bahrain",
      iso3: "BH",
      phone_code: "973",
      currency_code: "BHD",
      currency: "Bahraini dinar",
      emoji: "🇧🇭",
      emoji_unicode: "U+1F1E7 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: ".د.ب",
    },
    {
      id: 19,
      name: "Bangladesh",
      iso3: "BD",
      phone_code: "880",
      currency_code: "BDT",
      currency: "Bangladeshi taka",
      emoji: "🇧🇩",
      emoji_unicode: "U+1F1E7 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "৳",
    },
    {
      id: 20,
      name: "Barbados",
      iso3: "BB",
      phone_code: "+1-246",
      currency_code: "BBD",
      currency: "Barbadian dollar",
      emoji: "🇧🇧",
      emoji_unicode: "U+1F1E7 U+1F1E7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "Bds$",
    },
    {
      id: 21,
      name: "Belarus",
      iso3: "BY",
      phone_code: "375",
      currency_code: "BYN",
      currency: "Belarusian ruble",
      emoji: "🇧🇾",
      emoji_unicode: "U+1F1E7 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Br",
    },
    {
      id: 22,
      name: "Belgium",
      iso3: "BE",
      phone_code: "32",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇧🇪",
      emoji_unicode: "U+1F1E7 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 23,
      name: "Belize",
      iso3: "BZ",
      phone_code: "501",
      currency_code: "BZD",
      currency: "Belize dollar",
      emoji: "🇧🇿",
      emoji_unicode: "U+1F1E7 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 24,
      name: "Benin",
      iso3: "BJ",
      phone_code: "229",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇧🇯",
      emoji_unicode: "U+1F1E7 U+1F1EF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 25,
      name: "Bermuda",
      iso3: "BM",
      phone_code: "+1-441",
      currency_code: "BMD",
      currency: "Bermudian dollar",
      emoji: "🇧🇲",
      emoji_unicode: "U+1F1E7 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 26,
      name: "Bhutan",
      iso3: "BT",
      phone_code: "975",
      currency_code: "BTN",
      currency: "Bhutanese ngultrum",
      emoji: "🇧🇹",
      emoji_unicode: "U+1F1E7 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "Nu.",
    },
    {
      id: 27,
      name: "Bolivia",
      iso3: "BO",
      phone_code: "591",
      currency_code: "BOB",
      currency: "Bolivian boliviano",
      emoji: "🇧🇴",
      emoji_unicode: "U+1F1E7 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "Bs.",
    },
    {
      id: 155,
      name: "Bonaire, Sint Eustatius and Saba",
      iso3: "BQ",
      phone_code: "599",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇧🇶",
      emoji_unicode: "U+1F1E7 U+1F1F6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 28,
      name: "Bosnia and Herzegovina",
      iso3: "BA",
      phone_code: "387",
      currency_code: "BAM",
      currency: "Bosnia and Herzegovina convertible mark",
      emoji: "🇧🇦",
      emoji_unicode: "U+1F1E7 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "KM",
    },
    {
      id: 29,
      name: "Botswana",
      iso3: "BW",
      phone_code: "267",
      currency_code: "BWP",
      currency: "Botswana pula",
      emoji: "🇧🇼",
      emoji_unicode: "U+1F1E7 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "P",
    },
    {
      id: 30,
      name: "Bouvet Island",
      iso3: "BV",
      phone_code: "0055",
      currency_code: "NOK",
      currency: "Norwegian Krone",
      emoji: "🇧🇻",
      emoji_unicode: "U+1F1E7 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "kr",
    },
    {
      id: 31,
      name: "Brazil",
      iso3: "BR",
      phone_code: "55",
      currency_code: "BRL",
      currency: "Brazilian real",
      emoji: "🇧🇷",
      emoji_unicode: "U+1F1E7 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "R$",
    },
    {
      id: 32,
      name: "British Indian Ocean Territory",
      iso3: "IO",
      phone_code: "246",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇮🇴",
      emoji_unicode: "U+1F1EE U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 33,
      name: "Brunei",
      iso3: "BN",
      phone_code: "673",
      currency_code: "BND",
      currency: "Brunei dollar",
      emoji: "🇧🇳",
      emoji_unicode: "U+1F1E7 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "B$",
    },
    {
      id: 34,
      name: "Bulgaria",
      iso3: "BG",
      phone_code: "359",
      currency_code: "BGN",
      currency: "Bulgarian lev",
      emoji: "🇧🇬",
      emoji_unicode: "U+1F1E7 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Лв.",
    },
    {
      id: 35,
      name: "Burkina Faso",
      iso3: "BF",
      phone_code: "226",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇧🇫",
      emoji_unicode: "U+1F1E7 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 36,
      name: "Burundi",
      iso3: "BI",
      phone_code: "257",
      currency_code: "BIF",
      currency: "Burundian franc",
      emoji: "🇧🇮",
      emoji_unicode: "U+1F1E7 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FBu",
    },
    {
      id: 37,
      name: "Cambodia",
      iso3: "KH",
      phone_code: "855",
      currency_code: "KHR",
      currency: "Cambodian riel",
      emoji: "🇰🇭",
      emoji_unicode: "U+1F1F0 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "KHR",
    },
    {
      id: 38,
      name: "Cameroon",
      iso3: "CM",
      phone_code: "237",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇨🇲",
      emoji_unicode: "U+1F1E8 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FCFA",
    },
    {
      id: 39,
      name: "Canada",
      iso3: "CA",
      phone_code: "1",
      currency_code: "CAD",
      currency: "Canadian dollar",
      emoji: "🇨🇦",
      emoji_unicode: "U+1F1E8 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 40,
      name: "Cape Verde",
      iso3: "CV",
      phone_code: "238",
      currency_code: "CVE",
      currency: "Cape Verdean escudo",
      emoji: "🇨🇻",
      emoji_unicode: "U+1F1E8 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 41,
      name: "Cayman Islands",
      iso3: "KY",
      phone_code: "+1-345",
      currency_code: "KYD",
      currency: "Cayman Islands dollar",
      emoji: "🇰🇾",
      emoji_unicode: "U+1F1F0 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 42,
      name: "Central African Republic",
      iso3: "CF",
      phone_code: "236",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇨🇫",
      emoji_unicode: "U+1F1E8 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FCFA",
    },
    {
      id: 43,
      name: "Chad",
      iso3: "TD",
      phone_code: "235",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇹🇩",
      emoji_unicode: "U+1F1F9 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FCFA",
    },
    {
      id: 44,
      name: "Chile",
      iso3: "CL",
      phone_code: "56",
      currency_code: "CLP",
      currency: "Chilean peso",
      emoji: "🇨🇱",
      emoji_unicode: "U+1F1E8 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 45,
      name: "China",
      iso3: "CN",
      phone_code: "86",
      currency_code: "CNY",
      currency: "Chinese yuan",
      emoji: "🇨🇳",
      emoji_unicode: "U+1F1E8 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "¥",
    },
    {
      id: 46,
      name: "Christmas Island",
      iso3: "CX",
      phone_code: "61",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇨🇽",
      emoji_unicode: "U+1F1E8 U+1F1FD",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 47,
      name: "Cocos (Keeling) Islands",
      iso3: "CC",
      phone_code: "61",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇨🇨",
      emoji_unicode: "U+1F1E8 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 48,
      name: "Colombia",
      iso3: "CO",
      phone_code: "57",
      currency_code: "COP",
      currency: "Colombian peso",
      emoji: "🇨🇴",
      emoji_unicode: "U+1F1E8 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 49,
      name: "Comoros",
      iso3: "KM",
      phone_code: "269",
      currency_code: "KMF",
      currency: "Comorian franc",
      emoji: "🇰🇲",
      emoji_unicode: "U+1F1F0 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CF",
    },
    {
      id: 50,
      name: "Congo",
      iso3: "CG",
      phone_code: "242",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇨🇬",
      emoji_unicode: "U+1F1E8 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FC",
    },
    {
      id: 52,
      name: "Cook Islands",
      iso3: "CK",
      phone_code: "682",
      currency_code: "NZD",
      currency: "Cook Islands dollar",
      emoji: "🇨🇰",
      emoji_unicode: "U+1F1E8 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 53,
      name: "Costa Rica",
      iso3: "CR",
      phone_code: "506",
      currency_code: "CRC",
      currency: "Costa Rican colón",
      emoji: "🇨🇷",
      emoji_unicode: "U+1F1E8 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "₡",
    },
    {
      id: 54,
      name: "Cote D'Ivoire (Ivory Coast)",
      iso3: "CI",
      phone_code: "225",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇨🇮",
      emoji_unicode: "U+1F1E8 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 55,
      name: "Croatia",
      iso3: "HR",
      phone_code: "385",
      currency_code: "HRK",
      currency: "Croatian kuna",
      emoji: "🇭🇷",
      emoji_unicode: "U+1F1ED U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "kn",
    },
    {
      id: 56,
      name: "Cuba",
      iso3: "CU",
      phone_code: "53",
      currency_code: "CUP",
      currency: "Cuban peso",
      emoji: "🇨🇺",
      emoji_unicode: "U+1F1E8 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 249,
      name: "Curaçao",
      iso3: "CW",
      phone_code: "599",
      currency_code: "ANG",
      currency: "Netherlands Antillean guilder",
      emoji: "🇨🇼",
      emoji_unicode: "U+1F1E8 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "ƒ",
    },
    {
      id: 57,
      name: "Cyprus",
      iso3: "CY",
      phone_code: "357",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇨🇾",
      emoji_unicode: "U+1F1E8 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 58,
      name: "Czech Republic",
      iso3: "CZ",
      phone_code: "420",
      currency_code: "CZK",
      currency: "Czech koruna",
      emoji: "🇨🇿",
      emoji_unicode: "U+1F1E8 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Kč",
    },
    {
      id: 51,
      name: "Democratic Republic of the Congo",
      iso3: "CD",
      phone_code: "243",
      currency_code: "CDF",
      currency: "Congolese Franc",
      emoji: "🇨🇩",
      emoji_unicode: "U+1F1E8 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FC",
    },
    {
      id: 59,
      name: "Denmark",
      iso3: "DK",
      phone_code: "45",
      currency_code: "DKK",
      currency: "Danish krone",
      emoji: "🇩🇰",
      emoji_unicode: "U+1F1E9 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Kr.",
    },
    {
      id: 60,
      name: "Djibouti",
      iso3: "DJ",
      phone_code: "253",
      currency_code: "DJF",
      currency: "Djiboutian franc",
      emoji: "🇩🇯",
      emoji_unicode: "U+1F1E9 U+1F1EF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Fdj",
    },
    {
      id: 61,
      name: "Dominica",
      iso3: "DM",
      phone_code: "+1-767",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇩🇲",
      emoji_unicode: "U+1F1E9 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 62,
      name: "Dominican Republic",
      iso3: "DO",
      phone_code: "+1-809 and 1-829",
      currency_code: "DOP",
      currency: "Dominican peso",
      emoji: "🇩🇴",
      emoji_unicode: "U+1F1E9 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 64,
      name: "Ecuador",
      iso3: "EC",
      phone_code: "593",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇪🇨",
      emoji_unicode: "U+1F1EA U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 65,
      name: "Egypt",
      iso3: "EG",
      phone_code: "20",
      currency_code: "EGP",
      currency: "Egyptian pound",
      emoji: "🇪🇬",
      emoji_unicode: "U+1F1EA U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "ج.م",
    },
    {
      id: 66,
      name: "El Salvador",
      iso3: "SV",
      phone_code: "503",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇸🇻",
      emoji_unicode: "U+1F1F8 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 67,
      name: "Equatorial Guinea",
      iso3: "GQ",
      phone_code: "240",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇬🇶",
      emoji_unicode: "U+1F1EC U+1F1F6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FCFA",
    },
    {
      id: 68,
      name: "Eritrea",
      iso3: "ER",
      phone_code: "291",
      currency_code: "ERN",
      currency: "Eritrean nakfa",
      emoji: "🇪🇷",
      emoji_unicode: "U+1F1EA U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Nfk",
    },
    {
      id: 69,
      name: "Estonia",
      iso3: "EE",
      phone_code: "372",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇪🇪",
      emoji_unicode: "U+1F1EA U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 212,
      name: "Eswatini",
      iso3: "SZ",
      phone_code: "268",
      currency_code: "SZL",
      currency: "Lilangeni",
      emoji: "🇸🇿",
      emoji_unicode: "U+1F1F8 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "E",
    },
    {
      id: 70,
      name: "Ethiopia",
      iso3: "ET",
      phone_code: "251",
      currency_code: "ETB",
      currency: "Ethiopian birr",
      emoji: "🇪🇹",
      emoji_unicode: "U+1F1EA U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Nkf",
    },
    {
      id: 71,
      name: "Falkland Islands",
      iso3: "FK",
      phone_code: "500",
      currency_code: "FKP",
      currency: "Falkland Islands pound",
      emoji: "🇫🇰",
      emoji_unicode: "U+1F1EB U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 72,
      name: "Faroe Islands",
      iso3: "FO",
      phone_code: "298",
      currency_code: "DKK",
      currency: "Danish krone",
      emoji: "🇫🇴",
      emoji_unicode: "U+1F1EB U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Kr.",
    },
    {
      id: 73,
      name: "Fiji Islands",
      iso3: "FJ",
      phone_code: "679",
      currency_code: "FJD",
      currency: "Fijian dollar",
      emoji: "🇫🇯",
      emoji_unicode: "U+1F1EB U+1F1EF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "FJ$",
    },
    {
      id: 74,
      name: "Finland",
      iso3: "FI",
      phone_code: "358",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇫🇮",
      emoji_unicode: "U+1F1EB U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 75,
      name: "France",
      iso3: "FR",
      phone_code: "33",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇫🇷",
      emoji_unicode: "U+1F1EB U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 76,
      name: "French Guiana",
      iso3: "GF",
      phone_code: "594",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇬🇫",
      emoji_unicode: "U+1F1EC U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 77,
      name: "French Polynesia",
      iso3: "PF",
      phone_code: "689",
      currency_code: "XPF",
      currency: "CFP franc",
      emoji: "🇵🇫",
      emoji_unicode: "U+1F1F5 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "₣",
    },
    {
      id: 78,
      name: "French Southern Territories",
      iso3: "TF",
      phone_code: "262",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇹🇫",
      emoji_unicode: "U+1F1F9 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 10,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 79,
      name: "Gabon",
      iso3: "GA",
      phone_code: "241",
      currency_code: "XAF",
      currency: "Central African CFA franc",
      emoji: "🇬🇦",
      emoji_unicode: "U+1F1EC U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FCFA",
    },
    {
      id: 80,
      name: "Gambia The",
      iso3: "GM",
      phone_code: "220",
      currency_code: "GMD",
      currency: "Gambian dalasi",
      emoji: "🇬🇲",
      emoji_unicode: "U+1F1EC U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "D",
    },
    {
      id: 81,
      name: "Georgia",
      iso3: "GE",
      phone_code: "995",
      currency_code: "GEL",
      currency: "Georgian lari",
      emoji: "🇬🇪",
      emoji_unicode: "U+1F1EC U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "ლ",
    },
    {
      id: 82,
      name: "Germany",
      iso3: "DE",
      phone_code: "49",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇩🇪",
      emoji_unicode: "U+1F1E9 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 83,
      name: "Ghana",
      iso3: "GH",
      phone_code: "233",
      currency_code: "GHS",
      currency: "Ghanaian cedi",
      emoji: "🇬🇭",
      emoji_unicode: "U+1F1EC U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "GH₵",
    },
    {
      id: 84,
      name: "Gibraltar",
      iso3: "GI",
      phone_code: "350",
      currency_code: "GIP",
      currency: "Gibraltar pound",
      emoji: "🇬🇮",
      emoji_unicode: "U+1F1EC U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 85,
      name: "Greece",
      iso3: "GR",
      phone_code: "30",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇬🇷",
      emoji_unicode: "U+1F1EC U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 86,
      name: "Greenland",
      iso3: "GL",
      phone_code: "299",
      currency_code: "DKK",
      currency: "Danish krone",
      emoji: "🇬🇱",
      emoji_unicode: "U+1F1EC U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "Kr.",
    },
    {
      id: 87,
      name: "Grenada",
      iso3: "GD",
      phone_code: "+1-473",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇬🇩",
      emoji_unicode: "U+1F1EC U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 88,
      name: "Guadeloupe",
      iso3: "GP",
      phone_code: "590",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇬🇵",
      emoji_unicode: "U+1F1EC U+1F1F5",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 89,
      name: "Guam",
      iso3: "GU",
      phone_code: "+1-671",
      currency_code: "USD",
      currency: "US Dollar",
      emoji: "🇬🇺",
      emoji_unicode: "U+1F1EC U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 90,
      name: "Guatemala",
      iso3: "GT",
      phone_code: "502",
      currency_code: "GTQ",
      currency: "Guatemalan quetzal",
      emoji: "🇬🇹",
      emoji_unicode: "U+1F1EC U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "Q",
    },
    {
      id: 91,
      name: "Guernsey and Alderney",
      iso3: "GG",
      phone_code: "+44-1481",
      currency_code: "GBP",
      currency: "British pound",
      emoji: "🇬🇬",
      emoji_unicode: "U+1F1EC U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 92,
      name: "Guinea",
      iso3: "GN",
      phone_code: "224",
      currency_code: "GNF",
      currency: "Guinean franc",
      emoji: "🇬🇳",
      emoji_unicode: "U+1F1EC U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FG",
    },
    {
      id: 93,
      name: "Guinea-Bissau",
      iso3: "GW",
      phone_code: "245",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇬🇼",
      emoji_unicode: "U+1F1EC U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 94,
      name: "Guyana",
      iso3: "GY",
      phone_code: "592",
      currency_code: "GYD",
      currency: "Guyanese dollar",
      emoji: "🇬🇾",
      emoji_unicode: "U+1F1EC U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 95,
      name: "Haiti",
      iso3: "HT",
      phone_code: "509",
      currency_code: "HTG",
      currency: "Haitian gourde",
      emoji: "🇭🇹",
      emoji_unicode: "U+1F1ED U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "G",
    },
    {
      id: 96,
      name: "Heard Island and McDonald Islands",
      iso3: "HM",
      phone_code: "672",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇭🇲",
      emoji_unicode: "U+1F1ED U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 10,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 97,
      name: "Honduras",
      iso3: "HN",
      phone_code: "504",
      currency_code: "HNL",
      currency: "Honduran lempira",
      emoji: "🇭🇳",
      emoji_unicode: "U+1F1ED U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "L",
    },
    {
      id: 98,
      name: "Hong Kong S.A.R.",
      iso3: "HK",
      phone_code: "852",
      currency_code: "HKD",
      currency: "Hong Kong dollar",
      emoji: "🇭🇰",
      emoji_unicode: "U+1F1ED U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 99,
      name: "Hungary",
      iso3: "HU",
      phone_code: "36",
      currency_code: "HUF",
      currency: "Hungarian forint",
      emoji: "🇭🇺",
      emoji_unicode: "U+1F1ED U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "Ft",
    },
    {
      id: 100,
      name: "Iceland",
      iso3: "IS",
      phone_code: "354",
      currency_code: "ISK",
      currency: "Icelandic króna",
      emoji: "🇮🇸",
      emoji_unicode: "U+1F1EE U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "kr",
    },
    {
      id: 101,
      name: "India",
      iso3: "IN",
      phone_code: "91",
      currency_code: "INR",
      currency: "Indian rupee",
      emoji: "🇮🇳",
      emoji_unicode: "U+1F1EE U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₹",
    },
    {
      id: 102,
      name: "Indonesia",
      iso3: "ID",
      phone_code: "62",
      currency_code: "IDR",
      currency: "Indonesian rupiah",
      emoji: "🇮🇩",
      emoji_unicode: "U+1F1EE U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "Rp",
    },
    {
      id: 103,
      name: "Iran",
      iso3: "IR",
      phone_code: "98",
      currency_code: "IRR",
      currency: "Iranian rial",
      emoji: "🇮🇷",
      emoji_unicode: "U+1F1EE U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "﷼",
    },
    {
      id: 104,
      name: "Iraq",
      iso3: "IQ",
      phone_code: "964",
      currency_code: "IQD",
      currency: "Iraqi dinar",
      emoji: "🇮🇶",
      emoji_unicode: "U+1F1EE U+1F1F6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "د.ع",
    },
    {
      id: 105,
      name: "Ireland",
      iso3: "IE",
      phone_code: "353",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇮🇪",
      emoji_unicode: "U+1F1EE U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 106,
      name: "Israel",
      iso3: "IL",
      phone_code: "972",
      currency_code: "ILS",
      currency: "Israeli new shekel",
      emoji: "🇮🇱",
      emoji_unicode: "U+1F1EE U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "₪",
    },
    {
      id: 107,
      name: "Italy",
      iso3: "IT",
      phone_code: "39",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇮🇹",
      emoji_unicode: "U+1F1EE U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 108,
      name: "Jamaica",
      iso3: "JM",
      phone_code: "+1-876",
      currency_code: "JMD",
      currency: "Jamaican dollar",
      emoji: "🇯🇲",
      emoji_unicode: "U+1F1EF U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "J$",
    },
    {
      id: 109,
      name: "Japan",
      iso3: "JP",
      phone_code: "81",
      currency_code: "JPY",
      currency: "Japanese yen",
      emoji: "🇯🇵",
      emoji_unicode: "U+1F1EF U+1F1F5",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "¥",
    },
    {
      id: 110,
      name: "Jersey",
      iso3: "JE",
      phone_code: "+44-1534",
      currency_code: "GBP",
      currency: "British pound",
      emoji: "🇯🇪",
      emoji_unicode: "U+1F1EF U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 111,
      name: "Jordan",
      iso3: "JO",
      phone_code: "962",
      currency_code: "JOD",
      currency: "Jordanian dinar",
      emoji: "🇯🇴",
      emoji_unicode: "U+1F1EF U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "ا.د",
    },
    {
      id: 112,
      name: "Kazakhstan",
      iso3: "KZ",
      phone_code: "7",
      currency_code: "KZT",
      currency: "Kazakhstani tenge",
      emoji: "🇰🇿",
      emoji_unicode: "U+1F1F0 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "лв",
    },
    {
      id: 113,
      name: "Kenya",
      iso3: "KE",
      phone_code: "254",
      currency_code: "KES",
      currency: "Kenyan shilling",
      emoji: "🇰🇪",
      emoji_unicode: "U+1F1F0 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "KSh",
    },
    {
      id: 114,
      name: "Kiribati",
      iso3: "KI",
      phone_code: "686",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇰🇮",
      emoji_unicode: "U+1F1F0 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 248,
      name: "Kosovo",
      iso3: "XK",
      phone_code: "383",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇽🇰",
      emoji_unicode: "U+1F1FD U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 117,
      name: "Kuwait",
      iso3: "KW",
      phone_code: "965",
      currency_code: "KWD",
      currency: "Kuwaiti dinar",
      emoji: "🇰🇼",
      emoji_unicode: "U+1F1F0 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "ك.د",
    },
    {
      id: 118,
      name: "Kyrgyzstan",
      iso3: "KG",
      phone_code: "996",
      currency_code: "KGS",
      currency: "Kyrgyzstani som",
      emoji: "🇰🇬",
      emoji_unicode: "U+1F1F0 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "лв",
    },
    {
      id: 119,
      name: "Laos",
      iso3: "LA",
      phone_code: "856",
      currency_code: "LAK",
      currency: "Lao kip",
      emoji: "🇱🇦",
      emoji_unicode: "U+1F1F1 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₭",
    },
    {
      id: 120,
      name: "Latvia",
      iso3: "LV",
      phone_code: "371",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇱🇻",
      emoji_unicode: "U+1F1F1 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 121,
      name: "Lebanon",
      iso3: "LB",
      phone_code: "961",
      currency_code: "LBP",
      currency: "Lebanese pound",
      emoji: "🇱🇧",
      emoji_unicode: "U+1F1F1 U+1F1E7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 122,
      name: "Lesotho",
      iso3: "LS",
      phone_code: "266",
      currency_code: "LSL",
      currency: "Lesotho loti",
      emoji: "🇱🇸",
      emoji_unicode: "U+1F1F1 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "L",
    },
    {
      id: 123,
      name: "Liberia",
      iso3: "LR",
      phone_code: "231",
      currency_code: "LRD",
      currency: "Liberian dollar",
      emoji: "🇱🇷",
      emoji_unicode: "U+1F1F1 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 124,
      name: "Libya",
      iso3: "LY",
      phone_code: "218",
      currency_code: "LYD",
      currency: "Libyan dinar",
      emoji: "🇱🇾",
      emoji_unicode: "U+1F1F1 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "د.ل",
    },
    {
      id: 125,
      name: "Liechtenstein",
      iso3: "LI",
      phone_code: "423",
      currency_code: "CHF",
      currency: "Swiss franc",
      emoji: "🇱🇮",
      emoji_unicode: "U+1F1F1 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "CHf",
    },
    {
      id: 126,
      name: "Lithuania",
      iso3: "LT",
      phone_code: "370",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇱🇹",
      emoji_unicode: "U+1F1F1 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 127,
      name: "Luxembourg",
      iso3: "LU",
      phone_code: "352",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇱🇺",
      emoji_unicode: "U+1F1F1 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 128,
      name: "Macau S.A.R.",
      iso3: "MO",
      phone_code: "853",
      currency_code: "MOP",
      currency: "Macanese pataca",
      emoji: "🇲🇴",
      emoji_unicode: "U+1F1F2 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 130,
      name: "Madagascar",
      iso3: "MG",
      phone_code: "261",
      currency_code: "MGA",
      currency: "Malagasy ariary",
      emoji: "🇲🇬",
      emoji_unicode: "U+1F1F2 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Ar",
    },
    {
      id: 131,
      name: "Malawi",
      iso3: "MW",
      phone_code: "265",
      currency_code: "MWK",
      currency: "Malawian kwacha",
      emoji: "🇲🇼",
      emoji_unicode: "U+1F1F2 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "MK",
    },
    {
      id: 132,
      name: "Malaysia",
      iso3: "MY",
      phone_code: "60",
      currency_code: "MYR",
      currency: "Malaysian ringgit",
      emoji: "🇲🇾",
      emoji_unicode: "U+1F1F2 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "RM",
    },
    {
      id: 133,
      name: "Maldives",
      iso3: "MV",
      phone_code: "960",
      currency_code: "MVR",
      currency: "Maldivian rufiyaa",
      emoji: "🇲🇻",
      emoji_unicode: "U+1F1F2 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "Rf",
    },
    {
      id: 134,
      name: "Mali",
      iso3: "ML",
      phone_code: "223",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇲🇱",
      emoji_unicode: "U+1F1F2 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 135,
      name: "Malta",
      iso3: "MT",
      phone_code: "356",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇲🇹",
      emoji_unicode: "U+1F1F2 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 136,
      name: "Man (Isle of)",
      iso3: "IM",
      phone_code: "+44-1624",
      currency_code: "GBP",
      currency: "British pound",
      emoji: "🇮🇲",
      emoji_unicode: "U+1F1EE U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 137,
      name: "Marshall Islands",
      iso3: "MH",
      phone_code: "692",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇲🇭",
      emoji_unicode: "U+1F1F2 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 138,
      name: "Martinique",
      iso3: "MQ",
      phone_code: "596",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇲🇶",
      emoji_unicode: "U+1F1F2 U+1F1F6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 139,
      name: "Mauritania",
      iso3: "MR",
      phone_code: "222",
      currency_code: "MRO",
      currency: "Mauritanian ouguiya",
      emoji: "🇲🇷",
      emoji_unicode: "U+1F1F2 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "MRU",
    },
    {
      id: 140,
      name: "Mauritius",
      iso3: "MU",
      phone_code: "230",
      currency_code: "MUR",
      currency: "Mauritian rupee",
      emoji: "🇲🇺",
      emoji_unicode: "U+1F1F2 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "₨",
    },
    {
      id: 141,
      name: "Mayotte",
      iso3: "YT",
      phone_code: "262",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇾🇹",
      emoji_unicode: "U+1F1FE U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 142,
      name: "Mexico",
      iso3: "MX",
      phone_code: "52",
      currency_code: "MXN",
      currency: "Mexican peso",
      emoji: "🇲🇽",
      emoji_unicode: "U+1F1F2 U+1F1FD",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 143,
      name: "Micronesia",
      iso3: "FM",
      phone_code: "691",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇫🇲",
      emoji_unicode: "U+1F1EB U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 144,
      name: "Moldova",
      iso3: "MD",
      phone_code: "373",
      currency_code: "MDL",
      currency: "Moldovan leu",
      emoji: "🇲🇩",
      emoji_unicode: "U+1F1F2 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "L",
    },
    {
      id: 145,
      name: "Monaco",
      iso3: "MC",
      phone_code: "377",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇲🇨",
      emoji_unicode: "U+1F1F2 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 146,
      name: "Mongolia",
      iso3: "MN",
      phone_code: "976",
      currency_code: "MNT",
      currency: "Mongolian tögrög",
      emoji: "🇲🇳",
      emoji_unicode: "U+1F1F2 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₮",
    },
    {
      id: 147,
      name: "Montenegro",
      iso3: "ME",
      phone_code: "382",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇲🇪",
      emoji_unicode: "U+1F1F2 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 148,
      name: "Montserrat",
      iso3: "MS",
      phone_code: "+1-664",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇲🇸",
      emoji_unicode: "U+1F1F2 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 149,
      name: "Morocco",
      iso3: "MA",
      phone_code: "212",
      currency_code: "MAD",
      currency: "Moroccan dirham",
      emoji: "🇲🇦",
      emoji_unicode: "U+1F1F2 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "DH",
    },
    {
      id: 150,
      name: "Mozambique",
      iso3: "MZ",
      phone_code: "258",
      currency_code: "MZN",
      currency: "Mozambican metical",
      emoji: "🇲🇿",
      emoji_unicode: "U+1F1F2 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "MT",
    },
    {
      id: 151,
      name: "Myanmar",
      iso3: "MM",
      phone_code: "95",
      currency_code: "MMK",
      currency: "Burmese kyat",
      emoji: "🇲🇲",
      emoji_unicode: "U+1F1F2 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "K",
    },
    {
      id: 152,
      name: "Namibia",
      iso3: "NA",
      phone_code: "264",
      currency_code: "NAD",
      currency: "Namibian dollar",
      emoji: "🇳🇦",
      emoji_unicode: "U+1F1F3 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 153,
      name: "Nauru",
      iso3: "NR",
      phone_code: "674",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇳🇷",
      emoji_unicode: "U+1F1F3 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 154,
      name: "Nepal",
      iso3: "NP",
      phone_code: "977",
      currency_code: "NPR",
      currency: "Nepalese rupee",
      emoji: "🇳🇵",
      emoji_unicode: "U+1F1F3 U+1F1F5",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₨",
    },
    {
      id: 156,
      name: "Netherlands",
      iso3: "NL",
      phone_code: "31",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇳🇱",
      emoji_unicode: "U+1F1F3 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 157,
      name: "New Caledonia",
      iso3: "NC",
      phone_code: "687",
      currency_code: "XPF",
      currency: "CFP franc",
      emoji: "🇳🇨",
      emoji_unicode: "U+1F1F3 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "₣",
    },
    {
      id: 158,
      name: "New Zealand",
      iso3: "NZ",
      phone_code: "64",
      currency_code: "NZD",
      currency: "New Zealand dollar",
      emoji: "🇳🇿",
      emoji_unicode: "U+1F1F3 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 159,
      name: "Nicaragua",
      iso3: "NI",
      phone_code: "505",
      currency_code: "NIO",
      currency: "Nicaraguan córdoba",
      emoji: "🇳🇮",
      emoji_unicode: "U+1F1F3 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "C$",
    },
    {
      id: 160,
      name: "Niger",
      iso3: "NE",
      phone_code: "227",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇳🇪",
      emoji_unicode: "U+1F1F3 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 161,
      name: "Nigeria",
      iso3: "NG",
      phone_code: "234",
      currency_code: "NGN",
      currency: "Nigerian naira",
      emoji: "🇳🇬",
      emoji_unicode: "U+1F1F3 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "₦",
    },
    {
      id: 162,
      name: "Niue",
      iso3: "NU",
      phone_code: "683",
      currency_code: "NZD",
      currency: "New Zealand dollar",
      emoji: "🇳🇺",
      emoji_unicode: "U+1F1F3 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 163,
      name: "Norfolk Island",
      iso3: "NF",
      phone_code: "672",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇳🇫",
      emoji_unicode: "U+1F1F3 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 115,
      name: "North Korea",
      iso3: "KP",
      phone_code: "850",
      currency_code: "KPW",
      currency: "North Korean Won",
      emoji: "🇰🇵",
      emoji_unicode: "U+1F1F0 U+1F1F5",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₩",
    },
    {
      id: 129,
      name: "North Macedonia",
      iso3: "MK",
      phone_code: "389",
      currency_code: "MKD",
      currency: "Denar",
      emoji: "🇲🇰",
      emoji_unicode: "U+1F1F2 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "ден",
    },
    {
      id: 164,
      name: "Northern Mariana Islands",
      iso3: "MP",
      phone_code: "+1-670",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇲🇵",
      emoji_unicode: "U+1F1F2 U+1F1F5",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 165,
      name: "Norway",
      iso3: "NO",
      phone_code: "47",
      currency_code: "NOK",
      currency: "Norwegian krone",
      emoji: "🇳🇴",
      emoji_unicode: "U+1F1F3 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "kr",
    },
    {
      id: 166,
      name: "Oman",
      iso3: "OM",
      phone_code: "968",
      currency_code: "OMR",
      currency: "Omani rial",
      emoji: "🇴🇲",
      emoji_unicode: "U+1F1F4 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: ".ع.ر",
    },
    {
      id: 167,
      name: "Pakistan",
      iso3: "PK",
      phone_code: "92",
      currency_code: "PKR",
      currency: "Pakistani rupee",
      emoji: "🇵🇰",
      emoji_unicode: "U+1F1F5 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₨",
    },
    {
      id: 168,
      name: "Palau",
      iso3: "PW",
      phone_code: "680",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇵🇼",
      emoji_unicode: "U+1F1F5 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 169,
      name: "Palestinian Territory Occupied",
      iso3: "PS",
      phone_code: "970",
      currency_code: "ILS",
      currency: "Israeli new shekel",
      emoji: "🇵🇸",
      emoji_unicode: "U+1F1F5 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "₪",
    },
    {
      id: 170,
      name: "Panama",
      iso3: "PA",
      phone_code: "507",
      currency_code: "PAB",
      currency: "Panamanian balboa",
      emoji: "🇵🇦",
      emoji_unicode: "U+1F1F5 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 2,
      is_active: true,
      currency_symbol: "B/.",
    },
    {
      id: 171,
      name: "Papua New Guinea",
      iso3: "PG",
      phone_code: "675",
      currency_code: "PGK",
      currency: "Papua New Guinean kina",
      emoji: "🇵🇬",
      emoji_unicode: "U+1F1F5 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "K",
    },
    {
      id: 172,
      name: "Paraguay",
      iso3: "PY",
      phone_code: "595",
      currency_code: "PYG",
      currency: "Paraguayan guarani",
      emoji: "🇵🇾",
      emoji_unicode: "U+1F1F5 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "₲",
    },
    {
      id: 173,
      name: "Peru",
      iso3: "PE",
      phone_code: "51",
      currency_code: "PEN",
      currency: "Peruvian sol",
      emoji: "🇵🇪",
      emoji_unicode: "U+1F1F5 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "S/.",
    },
    {
      id: 174,
      name: "Philippines",
      iso3: "PH",
      phone_code: "63",
      currency_code: "PHP",
      currency: "Philippine peso",
      emoji: "🇵🇭",
      emoji_unicode: "U+1F1F5 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₱",
    },
    {
      id: 175,
      name: "Pitcairn Island",
      iso3: "PN",
      phone_code: "870",
      currency_code: "NZD",
      currency: "New Zealand dollar",
      emoji: "🇵🇳",
      emoji_unicode: "U+1F1F5 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 176,
      name: "Poland",
      iso3: "PL",
      phone_code: "48",
      currency_code: "PLN",
      currency: "Polish złoty",
      emoji: "🇵🇱",
      emoji_unicode: "U+1F1F5 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "zł",
    },
    {
      id: 177,
      name: "Portugal",
      iso3: "PT",
      phone_code: "351",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇵🇹",
      emoji_unicode: "U+1F1F5 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 178,
      name: "Puerto Rico",
      iso3: "PR",
      phone_code: "+1-787 and 1-939",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇵🇷",
      emoji_unicode: "U+1F1F5 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 179,
      name: "Qatar",
      iso3: "QA",
      phone_code: "974",
      currency_code: "QAR",
      currency: "Qatari riyal",
      emoji: "🇶🇦",
      emoji_unicode: "U+1F1F6 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "ق.ر",
    },
    {
      id: 180,
      name: "Reunion",
      iso3: "RE",
      phone_code: "262",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇷🇪",
      emoji_unicode: "U+1F1F7 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 181,
      name: "Romania",
      iso3: "RO",
      phone_code: "40",
      currency_code: "RON",
      currency: "Romanian leu",
      emoji: "🇷🇴",
      emoji_unicode: "U+1F1F7 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "lei",
    },
    {
      id: 182,
      name: "Russia",
      iso3: "RU",
      phone_code: "7",
      currency_code: "RUB",
      currency: "Russian ruble",
      emoji: "🇷🇺",
      emoji_unicode: "U+1F1F7 U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "₽",
    },
    {
      id: 183,
      name: "Rwanda",
      iso3: "RW",
      phone_code: "250",
      currency_code: "RWF",
      currency: "Rwandan franc",
      emoji: "🇷🇼",
      emoji_unicode: "U+1F1F7 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "FRw",
    },
    {
      id: 184,
      name: "Saint Helena",
      iso3: "SH",
      phone_code: "290",
      currency_code: "SHP",
      currency: "Saint Helena pound",
      emoji: "🇸🇭",
      emoji_unicode: "U+1F1F8 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 185,
      name: "Saint Kitts and Nevis",
      iso3: "KN",
      phone_code: "+1-869",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇰🇳",
      emoji_unicode: "U+1F1F0 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 186,
      name: "Saint Lucia",
      iso3: "LC",
      phone_code: "+1-758",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇱🇨",
      emoji_unicode: "U+1F1F1 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 187,
      name: "Saint Pierre and Miquelon",
      iso3: "PM",
      phone_code: "508",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇵🇲",
      emoji_unicode: "U+1F1F5 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 188,
      name: "Saint Vincent and the Grenadines",
      iso3: "VC",
      phone_code: "+1-784",
      currency_code: "XCD",
      currency: "Eastern Caribbean dollar",
      emoji: "🇻🇨",
      emoji_unicode: "U+1F1FB U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 189,
      name: "Saint-Barthelemy",
      iso3: "BL",
      phone_code: "590",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇧🇱",
      emoji_unicode: "U+1F1E7 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 190,
      name: "Saint-Martin (French part)",
      iso3: "MF",
      phone_code: "590",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇲🇫",
      emoji_unicode: "U+1F1F2 U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 191,
      name: "Samoa",
      iso3: "WS",
      phone_code: "685",
      currency_code: "WST",
      currency: "Samoan tālā",
      emoji: "🇼🇸",
      emoji_unicode: "U+1F1FC U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "SAT",
    },
    {
      id: 192,
      name: "San Marino",
      iso3: "SM",
      phone_code: "378",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇸🇲",
      emoji_unicode: "U+1F1F8 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 193,
      name: "Sao Tome and Principe",
      iso3: "ST",
      phone_code: "239",
      currency_code: "STD",
      currency: "Dobra",
      emoji: "🇸🇹",
      emoji_unicode: "U+1F1F8 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Db",
    },
    {
      id: 194,
      name: "Saudi Arabia",
      iso3: "SA",
      phone_code: "966",
      currency_code: "SAR",
      currency: "Saudi riyal",
      emoji: "🇸🇦",
      emoji_unicode: "U+1F1F8 U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "﷼",
    },
    {
      id: 195,
      name: "Senegal",
      iso3: "SN",
      phone_code: "221",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇸🇳",
      emoji_unicode: "U+1F1F8 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 196,
      name: "Serbia",
      iso3: "RS",
      phone_code: "381",
      currency_code: "RSD",
      currency: "Serbian dinar",
      emoji: "🇷🇸",
      emoji_unicode: "U+1F1F7 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "din",
    },
    {
      id: 197,
      name: "Seychelles",
      iso3: "SC",
      phone_code: "248",
      currency_code: "SCR",
      currency: "Seychellois rupee",
      emoji: "🇸🇨",
      emoji_unicode: "U+1F1F8 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "SRe",
    },
    {
      id: 198,
      name: "Sierra Leone",
      iso3: "SL",
      phone_code: "232",
      currency_code: "SLL",
      currency: "Sierra Leonean leone",
      emoji: "🇸🇱",
      emoji_unicode: "U+1F1F8 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Le",
    },
    {
      id: 199,
      name: "Singapore",
      iso3: "SG",
      phone_code: "65",
      currency_code: "SGD",
      currency: "Singapore dollar",
      emoji: "🇸🇬",
      emoji_unicode: "U+1F1F8 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 250,
      name: "Sint Maarten (Dutch part)",
      iso3: "SX",
      phone_code: "1721",
      currency_code: "ANG",
      currency: "Netherlands Antillean guilder",
      emoji: "🇸🇽",
      emoji_unicode: "U+1F1F8 U+1F1FD",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "ƒ",
    },
    {
      id: 200,
      name: "Slovakia",
      iso3: "SK",
      phone_code: "421",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇸🇰",
      emoji_unicode: "U+1F1F8 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 201,
      name: "Slovenia",
      iso3: "SI",
      phone_code: "386",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇸🇮",
      emoji_unicode: "U+1F1F8 U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 202,
      name: "Solomon Islands",
      iso3: "SB",
      phone_code: "677",
      currency_code: "SBD",
      currency: "Solomon Islands dollar",
      emoji: "🇸🇧",
      emoji_unicode: "U+1F1F8 U+1F1E7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "Si$",
    },
    {
      id: 203,
      name: "Somalia",
      iso3: "SO",
      phone_code: "252",
      currency_code: "SOS",
      currency: "Somali shilling",
      emoji: "🇸🇴",
      emoji_unicode: "U+1F1F8 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "Sh.so.",
    },
    {
      id: 204,
      name: "South Africa",
      iso3: "ZA",
      phone_code: "27",
      currency_code: "ZAR",
      currency: "South African rand",
      emoji: "🇿🇦",
      emoji_unicode: "U+1F1FF U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "R",
    },
    {
      id: 205,
      name: "South Georgia",
      iso3: "GS",
      phone_code: "500",
      currency_code: "GBP",
      currency: "British pound",
      emoji: "🇬🇸",
      emoji_unicode: "U+1F1EC U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 10,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 116,
      name: "South Korea",
      iso3: "KR",
      phone_code: "82",
      currency_code: "KRW",
      currency: "Won",
      emoji: "🇰🇷",
      emoji_unicode: "U+1F1F0 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₩",
    },
    {
      id: 206,
      name: "South Sudan",
      iso3: "SS",
      phone_code: "211",
      currency_code: "SSP",
      currency: "South Sudanese pound",
      emoji: "🇸🇸",
      emoji_unicode: "U+1F1F8 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 207,
      name: "Spain",
      iso3: "ES",
      phone_code: "34",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇪🇸",
      emoji_unicode: "U+1F1EA U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 208,
      name: "Sri Lanka",
      iso3: "LK",
      phone_code: "94",
      currency_code: "LKR",
      currency: "Sri Lankan rupee",
      emoji: "🇱🇰",
      emoji_unicode: "U+1F1F1 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "Rs",
    },
    {
      id: 209,
      name: "Sudan",
      iso3: "SD",
      phone_code: "249",
      currency_code: "SDG",
      currency: "Sudanese pound",
      emoji: "🇸🇩",
      emoji_unicode: "U+1F1F8 U+1F1E9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: ".س.ج",
    },
    {
      id: 210,
      name: "Suriname",
      iso3: "SR",
      phone_code: "597",
      currency_code: "SRD",
      currency: "Surinamese dollar",
      emoji: "🇸🇷",
      emoji_unicode: "U+1F1F8 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 211,
      name: "Svalbard and Jan Mayen Islands",
      iso3: "SJ",
      phone_code: "47",
      currency_code: "NOK",
      currency: "Norwegian Krone",
      emoji: "🇸🇯",
      emoji_unicode: "U+1F1F8 U+1F1EF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "kr",
    },
    {
      id: 213,
      name: "Sweden",
      iso3: "SE",
      phone_code: "46",
      currency_code: "SEK",
      currency: "Swedish krona",
      emoji: "🇸🇪",
      emoji_unicode: "U+1F1F8 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "kr",
    },
    {
      id: 214,
      name: "Switzerland",
      iso3: "CH",
      phone_code: "41",
      currency_code: "CHF",
      currency: "Swiss franc",
      emoji: "🇨🇭",
      emoji_unicode: "U+1F1E8 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "CHf",
    },
    {
      id: 215,
      name: "Syria",
      iso3: "SY",
      phone_code: "963",
      currency_code: "SYP",
      currency: "Syrian pound",
      emoji: "🇸🇾",
      emoji_unicode: "U+1F1F8 U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "LS",
    },
    {
      id: 216,
      name: "Taiwan",
      iso3: "TW",
      phone_code: "886",
      currency_code: "TWD",
      currency: "New Taiwan dollar",
      emoji: "🇹🇼",
      emoji_unicode: "U+1F1F9 U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 217,
      name: "Tajikistan",
      iso3: "TJ",
      phone_code: "992",
      currency_code: "TJS",
      currency: "Tajikistani somoni",
      emoji: "🇹🇯",
      emoji_unicode: "U+1F1F9 U+1F1EF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "SM",
    },
    {
      id: 218,
      name: "Tanzania",
      iso3: "TZ",
      phone_code: "255",
      currency_code: "TZS",
      currency: "Tanzanian shilling",
      emoji: "🇹🇿",
      emoji_unicode: "U+1F1F9 U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "TSh",
    },
    {
      id: 219,
      name: "Thailand",
      iso3: "TH",
      phone_code: "66",
      currency_code: "THB",
      currency: "Thai baht",
      emoji: "🇹🇭",
      emoji_unicode: "U+1F1F9 U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "฿",
    },
    {
      id: 17,
      name: "The Bahamas",
      iso3: "BS",
      phone_code: "+1-242",
      currency_code: "BSD",
      currency: "Bahamian dollar",
      emoji: "🇧🇸",
      emoji_unicode: "U+1F1E7 U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "B$",
    },
    {
      id: 63,
      name: "Timor-Leste",
      iso3: "TL",
      phone_code: "670",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇹🇱",
      emoji_unicode: "U+1F1F9 U+1F1F1",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 220,
      name: "Togo",
      iso3: "TG",
      phone_code: "228",
      currency_code: "XOF",
      currency: "West African CFA franc",
      emoji: "🇹🇬",
      emoji_unicode: "U+1F1F9 U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "CFA",
    },
    {
      id: 221,
      name: "Tokelau",
      iso3: "TK",
      phone_code: "690",
      currency_code: "NZD",
      currency: "New Zealand dollar",
      emoji: "🇹🇰",
      emoji_unicode: "U+1F1F9 U+1F1F0",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 222,
      name: "Tonga",
      iso3: "TO",
      phone_code: "676",
      currency_code: "TOP",
      currency: "Tongan paʻanga",
      emoji: "🇹🇴",
      emoji_unicode: "U+1F1F9 U+1F1F4",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 223,
      name: "Trinidad and Tobago",
      iso3: "TT",
      phone_code: "+1-868",
      currency_code: "TTD",
      currency: "Trinidad and Tobago dollar",
      emoji: "🇹🇹",
      emoji_unicode: "U+1F1F9 U+1F1F9",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 224,
      name: "Tunisia",
      iso3: "TN",
      phone_code: "216",
      currency_code: "TND",
      currency: "Tunisian dinar",
      emoji: "🇹🇳",
      emoji_unicode: "U+1F1F9 U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "ت.د",
    },
    {
      id: 225,
      name: "Turkey",
      iso3: "TR",
      phone_code: "90",
      currency_code: "TRY",
      currency: "Turkish lira",
      emoji: "🇹🇷",
      emoji_unicode: "U+1F1F9 U+1F1F7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "₺",
    },
    {
      id: 226,
      name: "Turkmenistan",
      iso3: "TM",
      phone_code: "993",
      currency_code: "TMT",
      currency: "Turkmenistan manat",
      emoji: "🇹🇲",
      emoji_unicode: "U+1F1F9 U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "T",
    },
    {
      id: 227,
      name: "Turks and Caicos Islands",
      iso3: "TC",
      phone_code: "+1-649",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇹🇨",
      emoji_unicode: "U+1F1F9 U+1F1E8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 228,
      name: "Tuvalu",
      iso3: "TV",
      phone_code: "688",
      currency_code: "AUD",
      currency: "Australian dollar",
      emoji: "🇹🇻",
      emoji_unicode: "U+1F1F9 U+1F1FB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 229,
      name: "Uganda",
      iso3: "UG",
      phone_code: "256",
      currency_code: "UGX",
      currency: "Ugandan shilling",
      emoji: "🇺🇬",
      emoji_unicode: "U+1F1FA U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "USh",
    },
    {
      id: 230,
      name: "Ukraine",
      iso3: "UA",
      phone_code: "380",
      currency_code: "UAH",
      currency: "Ukrainian hryvnia",
      emoji: "🇺🇦",
      emoji_unicode: "U+1F1FA U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "₴",
    },
    {
      id: 231,
      name: "United Arab Emirates",
      iso3: "AE",
      phone_code: "971",
      currency_code: "AED",
      currency: "United Arab Emirates dirham",
      emoji: "🇦🇪",
      emoji_unicode: "U+1F1E6 U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "إ.د",
    },
    {
      id: 232,
      name: "United Kingdom",
      iso3: "GB",
      phone_code: "44",
      currency_code: "GBP",
      currency: "British pound",
      emoji: "🇬🇧",
      emoji_unicode: "U+1F1EC U+1F1E7",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "£",
    },
    {
      id: 233,
      name: "United States",
      iso3: "US",
      phone_code: "1",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇺🇸",
      emoji_unicode: "U+1F1FA U+1F1F8",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 1,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 234,
      name: "United States Minor Outlying Islands",
      iso3: "UM",
      phone_code: "1",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇺🇲",
      emoji_unicode: "U+1F1FA U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 235,
      name: "Uruguay",
      iso3: "UY",
      phone_code: "598",
      currency_code: "UYU",
      currency: "Uruguayan peso",
      emoji: "🇺🇾",
      emoji_unicode: "U+1F1FA U+1F1FE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 236,
      name: "Uzbekistan",
      iso3: "UZ",
      phone_code: "998",
      currency_code: "UZS",
      currency: "Uzbekistani soʻm",
      emoji: "🇺🇿",
      emoji_unicode: "U+1F1FA U+1F1FF",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "лв",
    },
    {
      id: 237,
      name: "Vanuatu",
      iso3: "VU",
      phone_code: "678",
      currency_code: "VUV",
      currency: "Vanuatu vatu",
      emoji: "🇻🇺",
      emoji_unicode: "U+1F1FB U+1F1FA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "VT",
    },
    {
      id: 238,
      name: "Vatican City State (Holy See)",
      iso3: "VA",
      phone_code: "379",
      currency_code: "EUR",
      currency: "Euro",
      emoji: "🇻🇦",
      emoji_unicode: "U+1F1FB U+1F1E6",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 5,
      is_active: true,
      currency_symbol: "€",
    },
    {
      id: 239,
      name: "Venezuela",
      iso3: "VE",
      phone_code: "58",
      currency_code: "VES",
      currency: "Bolívar",
      emoji: "🇻🇪",
      emoji_unicode: "U+1F1FB U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 3,
      is_active: true,
      currency_symbol: "Bs",
    },
    {
      id: 240,
      name: "Vietnam",
      iso3: "VN",
      phone_code: "84",
      currency_code: "VND",
      currency: "Vietnamese đồng",
      emoji: "🇻🇳",
      emoji_unicode: "U+1F1FB U+1F1F3",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 8,
      is_active: true,
      currency_symbol: "₫",
    },
    {
      id: 241,
      name: "Virgin Islands (British)",
      iso3: "VG",
      phone_code: "+1-284",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇻🇬",
      emoji_unicode: "U+1F1FB U+1F1EC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 242,
      name: "Virgin Islands (US)",
      iso3: "VI",
      phone_code: "+1-340",
      currency_code: "USD",
      currency: "United States dollar",
      emoji: "🇻🇮",
      emoji_unicode: "U+1F1FB U+1F1EE",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 4,
      is_active: true,
      currency_symbol: "$",
    },
    {
      id: 243,
      name: "Wallis and Futuna Islands",
      iso3: "WF",
      phone_code: "681",
      currency_code: "XPF",
      currency: "CFP franc",
      emoji: "🇼🇫",
      emoji_unicode: "U+1F1FC U+1F1EB",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 9,
      is_active: true,
      currency_symbol: "₣",
    },
    {
      id: 244,
      name: "Western Sahara",
      iso3: "EH",
      phone_code: "212",
      currency_code: "MAD",
      currency: "Moroccan Dirham",
      emoji: "🇪🇭",
      emoji_unicode: "U+1F1EA U+1F1ED",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "MAD",
    },
    {
      id: 245,
      name: "Yemen",
      iso3: "YE",
      phone_code: "967",
      currency_code: "YER",
      currency: "Yemeni rial",
      emoji: "🇾🇪",
      emoji_unicode: "U+1F1FE U+1F1EA",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 7,
      is_active: true,
      currency_symbol: "﷼",
    },
    {
      id: 246,
      name: "Zambia",
      iso3: "ZM",
      phone_code: "260",
      currency_code: "ZMW",
      currency: "Zambian kwacha",
      emoji: "🇿🇲",
      emoji_unicode: "U+1F1FF U+1F1F2",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "ZK",
    },
    {
      id: 247,
      name: "Zimbabwe",
      iso3: "ZW",
      phone_code: "263",
      currency_code: "ZWL",
      currency: "Zimbabwe Dollar",
      emoji: "🇿🇼",
      emoji_unicode: "U+1F1FF U+1F1FC",
      created_at: new Date(),
      updated_at: new Date(),
      region_id: 6,
      is_active: true,
      currency_symbol: "$",
    },
  ],
};
