import {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
  GET_INVESTOR_LIST,
  GET_INVESTOR_LIST_AS_CSV,
} from "./get";

export default {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
  GET_INVESTOR_LIST,
  GET_INVESTOR_LIST_AS_CSV,
};
