import {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
} from "./get";

export default {
  GET_ORDERS_GRAPH,
  GET_TOKEN_BY_INVESTOR_GRAPH,
  GET_DASHBOARD,
  GET_FUND_OFFERINGS,
};
